/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class l2d_Java2CPPTest */

#ifndef _Included_l2d_Java2CPPTest
#define _Included_l2d_Java2CPPTest
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     l2d_Java2CPPTest
	 * Method:    initializeL2DApp
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_l2d_Java2CPPTest_initializeL2DApp
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
