/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class l2d_Java2CPPDefine */

#ifndef _Included_l2d_Java2CPPDefine
#define _Included_l2d_Java2CPPDefine
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     l2d_Java2CPPDefine
	 * Method:    initializeL2DApp
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_l2d_Java2CPPDefine_initializeL2DApp
	(JNIEnv*, jobject);

	/*
	 * Class:     l2d_Java2CPPDefine
	 * Method:    startMotion
	 * Signature: (Ljava/lang/String;IILl2d/Java2CPPDefine/MotionCallback;)V
	 */
	JNIEXPORT void JNICALL Java_l2d_Java2CPPDefine_startMotion
	(JNIEnv*, jobject, jstring, jint, jint, jobject);

	/*
	 * Class:     l2d_Java2CPPDefine
	 * Method:    startRandomMotion
	 * Signature: (Ljava/lang/String;ILl2d/Java2CPPDefine/MotionCallback;)V
	 */
	JNIEXPORT void JNICALL Java_l2d_Java2CPPDefine_startRandomMotion
	(JNIEnv*, jobject, jstring, jint, jobject);

	/*
	 * Class:     l2d_Java2CPPDefine
	 * Method:    setExpression
	 * Signature: (Ljava/lang/String;)V
	 */
	JNIEXPORT void JNICALL Java_l2d_Java2CPPDefine_setExpression
	(JNIEnv*, jobject, jstring);

	/*
	 * Class:     l2d_Java2CPPDefine
	 * Method:    setRandomExpression
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_l2d_Java2CPPDefine_setRandomExpression
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
